// 指令工具类
export default {
  // 通知改变
  NOTIFY_STATUS_CHANGE: "NOTIFY_STATUS_CHANGE",
  // 检验秘钥请求
  CHECK_SECRET_REQUEST: "CHECK_SECRET_REQUEST",
  // 秘钥校验结果
  CHECK_SECRET_RESULT: "CHECK_SECRET_RESULT",
  // 恢复出厂设置请求
  RESTORE_FACTORY_SETTINGS_REQUEST: "RESTORE_FACTORY_SETTINGS_REQUEST",
  // 恢复出厂设置应答
  RESTORE_FACTORY_SETTINGS_RESPONSE: "RESTORE_FACTORY_SETTINGS_RESPONSE",
  // 恢复出厂设置结果
  RESTORE_FACTORY_SETTINGS_RESULT: "RESTORE_FACTORY_SETTINGS_RESULT",
  // 关机请求
  SHUTDOWN_REQUEST: "SHUTDOWN_REQUEST",
  // 关机响应
  SHUTDOWN_RESPONSE: "SHUTDOWN_RESPONSE",
  // 关机结果
  SHUTDOWN_RESULT: "SHUTDOWN_RESULT",
  // 删除秘钥请求
  REMOVE_SECRET_KEY_REQUEST: "REMOVE_SECRET_KEY_REQUEST",
  // 删除秘钥结果
  REMOVE_SECRET_KEY_RESULT: "REMOVE_SECRET_KEY_RESULT",
  // 修改秘钥请求
  UPDATE_SECRET_KEY_REQUEST: "UPDATE_SECRET_KEY_REQUEST",
  // 修改秘钥结果
  UPDATE_SECRET_KEY_RESULT: "UPDATE_SECRET_KEY_RESULT",
  // 读取出厂信息请求
  READ_FACTORY_VERSION_INFO_REQUEST: "READ_FACTORY_VERSION_INFO_REQUEST",
  // 读取出厂信息应答
  READ_FACTORY_VERSION_INFO_RESPONSE: "READ_FACTORY_VERSION_INFO_RESPONSE",
  // 读取出厂信息结果
  READ_FACTORY_VERSION_INFO_RESULT: "READ_FACTORY_VERSION_INFO_RESULT",
  // 读取特征信息请求
  READ_FEATURE_INFO_REQUEST: "READ_FEATURE_INFO_REQUEST",
  // 读取特征信息应答
  READ_FEATURE_INFO_RESPONSE: "READ_FEATURE_INFO_RESPONSE",
  // 读取特征信息结果
  READ_FEATURE_INFO_RESULT: "READ_FEATURE_INFO_RESULT",
  // 查询配置协议
  QUERY_CONFIG_AGREEMENT_REQUEST: "QUERY_CONFIG_AGREEMENT_REQUEST",
  // 查询配置协议结果
  QUERY_CONFIG_AGREEMENT_RESULT: "QUERY_CONFIG_AGREEMENT_RESULT",

  // 是否需要秘钥请求
  NEED_SECRET_CONNECT_REQUEST: "NEED_SECRET_CONNECT_REQUEST",
  // 是否需要秘钥结果
  NEED_SECRET_CONNECT_RESULT: "NEED_SECRET_CONNECT_RESULT",

  // 通道配置响应
  CHANNEL_CONFIG_BEACON_RESPONSE: "CHANNEL_CONFIG_BEACON_RESPONSE",
  // 通道配置结果
  CHANNEL_CONFIG_BEACON_RESULT: "CHANNEL_CONFIG_BEACON_RESULT",

  // 设置不可连接
  NOT_CONNECTABLE_CONFIG_REQUEST: "NOT_CONNECTABLE_CONFIG_REQUEST",
  NOT_CONNECTABLE_CONFIG_RESULT: "NOT_CONNECTABLE_CONFIG_RESULT",

  // 触发响应时间
  TRIGGER_RESPONSE_TIME_CONFIG_REQUEST: "TRIGGER_RESPONSE_TIME_CONFIG_REQUEST",
  TRIGGER_RESPONSE_TIME_CONFIG_RESULT: "TRIGGER_RESPONSE_TIME_CONFIG_RESULT",

  // 重启信标
  RESTART_BEACON_REQUEST: "RESTART_BEACON_REQUEST",
  RESTART_BEACON_RESULT: "RESTART_BEACON_RESULT",
};
